### ISSUE TITLE
Create continuous build automation

### ISSUE THREAD

**Issue by danfma** [kodando/kodando#14]
Add a Circle CI automating to build, execute the tests (we need more tests... I know!), and publish to Bintray.

## Idea:

- Each branch should be compiled and tested, before merging the PR to the develop branch;
- Every time that the developer branch gets a new commit, then it should execute the automation and if everything is OK, then merge to the master branch;
- Every time that the master branch gets a new commit, then it should be published to the Bintray repository.

**Comment by felipehjcosta** [comment]
Nice! I usually use Travis CI in my projects. :)

**Comment by felipehjcosta** [comment]
I think only you can create the account on Circle Ci

**Comment by felipehjcosta** [comment]
Oh, the CI idea you described should be part of the contribution guide. What do you think?

**Comment by danfma** [comment]
I agree with your idea! Do you prefer to use the Travis?

**Comment by felipehjcosta** [comment]
Yes, I think it is more suitable for open source projects.

**Comment by danfma** [comment]
I don't mind using Travis. I chose the CircleCI because of recommendations too. I will create the account there, but you are listed as a contributor now. Later we could talk about how to define the build and publishing tasks.

**Comment by felipehjcosta** [comment]
I pushed a new branch using Travis CI but I couldn't enabled it. I think you need to add it:

![screen shot 2018-03-24 at 15 50 41](https://user-images.githubusercontent.com/2865924/37867721-1f70ceee-2f7b-11e8-881a-46f500bd93d2.png)

**Comment by danfma** [comment]
Ok, let me see that!

**Comment by danfma** [comment]
I will merge your branch with the develop branch, so we can configure it properly.

**Comment by danfma** [comment]
I already integrated your feature branch and created a PR for it. Give a look at there!
Now we should verify how to auto-publish to Bintray when merging from developer to master.

**Comment by felipehjcosta** [comment]
I approved the PR. 
Yes! I will take a look at auto-publish integration and create a PR for it.

I know that is not in the context of this issue, but have you ever heard of [this plugin]?(https://github.com/srs/gradle-node-plugin/blob/master/docs/node.md)

**Comment by danfma** [comment]
Is this the tool that downloads and executes the node within Gradle? I think that I already used sometimes, but I don't remember why I'm not using it anymore. Maybe, because I want the structure clean to execute the tests with jest, but we can check that too for a better developer experience. Just create a new investigation ticket for this.

**Comment by felipehjcosta** [comment]
Done!

**Comment by felipehjcosta** [comment]
I think we can close this issue now :)
