### ISSUE TITLE
Bindings for react native

### ISSUE THREAD

**Issue by denisidoro** [kodando/kodando#2]
Any plans on adding bindings for react native?
As of now, using [ts2kt](https://github.com/Kotlin/ts2kt) results into [errors](https://github.com/Kotlin/ts2kt/issues/44).
By the way, nice work!

**Comment by danfma** [comment]
Thanks, man! I could start creating the bindings but first I need to investigate its API. Right now, my focus is only the Web but the React Native is really a nice feature that I could try. Let's keep the contact.

**Comment by danfma** [comment]
Ops, I closed it by mistake.
