### ISSUE TITLE
Rewrite the build scripts in kotlin (kscript)

### ISSUE THREAD

**Issue by danfma** [kodando/kodando#39]
Let's check the possibility of writing the build scripts in Kotlin and the positive/negative points.

**Comment by felipehjcosta** [comment]
I have some mixed feelings about it... 

Positive points:
* Kotlin S2
* IDE support 

Negative points:
* Lack of documentation
* IDE support is terrible slow

I have a sample project that uses it: https://github.com/felipehjcosta/kotlin-microservice

**Comment by danfma** [comment]
Sure! I agree. I think that maybe it will be slower than simple scripts in JavaScript. So, let's keep the JavaScript scripts for now.
