### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by felipehjcosta** [kodando/kodando#9]
Hi,

How can I contribute to the project? Is there any guidelines?

**Comment by danfma** [comment]
Hey, I'm glad to know about that!

Actually, I don't have guidelines because I was the only one working on the project but we can define one together. What do you think? The JetBrains coding style could be the default one.

**Comment by felipehjcosta** [comment]
Sure! We should stick with the JetBrains coding style. :)

**Comment by felipehjcosta** [comment]
Btw, what do you think about adding some CI to the project?

**Comment by danfma** [comment]
I agree with the CI too. I will explain how I'm doing the things today later.

**Comment by danfma** [comment]
Maybe we should create an organization for the project too.

**Comment by felipehjcosta** [comment]
I agree with the organization too. It's been a while since I'd like to contribute to open source and I love Kotlin. So, I started an evaluation of Kotlin with Javascript and I found out the lack of bindings for javascript (except the JetBrains ones). Kotlin bindings is something that I would like to know more too! (Kotlin Native is coming) :)

**Comment by danfma** [comment]
Topics to be discussed:

- Versioning and parity with js libraries;
- Tests;
- CI;
- Samples;
- Documentation.

**Comment by felipehjcosta** [comment]
Good points. Since we already have multiple modules, it will be simple to break them into projects.
What git flow and versioning strategy do you think we should follow?

**Comment by danfma** [comment]
Let's write about the branching policy here https://github.com/kodando/kodando/wiki/Contribution.

**Comment by felipehjcosta** [comment]
I agree with the `git flow` and `versioning` policies and I wrote a draft about the branching policy.

I personally like the way [this](https://github.com/JakeWharton/RxBinding) repository is organized.

**Comment by danfma** [comment]
@felipehjcosta This next week I will try to be more active here. So we could talk more about the project evolution.

**Comment by felipehjcosta** [comment]
Sorry fo the delay, I didn't have much time in the last two weeks :(

I was thinking about your question and the repository I sent follows an approach which fits better on a single library. But we can use the same idea for versioning if you would like!
